services:
  nginx:
    image: nginx_sprint_3
    container_name: nginx
    restart: "always"
    volumes:
      - static_volume:/opt/app/static/:ro
    ports:
      - "80:80"
    depends_on:
      - movies_admin

  etl:
    image: etl_sprint_3
    container_name: etl
    restart: "always"
    env_file:
      - .env
    depends_on:
      - postgres
      - elasticsearch

  movies_admin:
    image: movies_admin_sprint_3
    container_name: movies_admin
    restart: "always"
    volumes:
      - static_volume:/opt/app/static/
    env_file:
      - .env
    depends_on:
      - postgres

  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    restart: "always"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      # change settings for real production service
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ulimits:
      # change settings for real production service
      nofile:
        soft: 65536
        hard: 65536

  postgres:
    image: postgres_sprint_3
    container_name: postgres
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

volumes:
  elasticsearch_data:
  postgres_data:
  static_volume: